version: '3.7'

services:
  db:
    image: postgres:13.16
    networks:
      - backend
    environment:
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5000:5432"

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    networks:
      - backend
    ports:
      - 3000:3000
    environment:
      - DATABASE_HOST=${DB_HOST}
      - DATABASE_PORT=${DB_PORT}
      - DATABASE_USER=${DB_USER}
      - DATABASE_PASSWORD=${DB_PASS}
      - DATABASE_NAME=${DB_NAME}
    env_file:
      - .env
networks:
  backend: